### ISSUE TITLE
IRQn problem after upgrading from 1.12.0 to 4.6.1

### ISSUE THREAD

**Issue by JdeV987** [earlephilhower/arduino-pico#3054]
When using this board definition (for a Raspberry-Pi Pico), this code worked before: 
 `irq_tab[TIMER_IRQ_0_IRQn] = (uint32_t)TIMER_IRQ_0_IRQHandler; // Vektor ins RAM`

Now with 4.6.1, I get this error: 
"Compilation error: 'TIMER_IRQ_0_IRQn' was not declared in this scope; did you mean 'TIMER_IRQ_0'? "

Any idea why and how to fix it?

Thank you.
John
