### ISSUE TITLE
esphome fails to compile with 4.2.0 release due to conflicting decls of cyw43_hal_generate_laa_mac

### ISSUE THREAD

**Issue by afflux** [earlephilhower/arduino-pico#2602]
When including both `WiFi.h` and `cyw43.h`, I get this compile error:
```
~/.platformio/packages/framework-arduinopico/libraries/lwIP_Ethernet/src/LwipIntfDev.h:57:17: error: 'void cyw43_hal_generate_laa_mac(int, uint8_t*)' was declared 'extern' and later 'static' [-fpermissive]
```

`cyw43_hal_generate_laa_mac` is defined here as `static`:
https://github.com/earlephilhower/arduino-pico/blob/db4b167aaafc33d235d2b1f1949fcae8d107c10e/libraries/lwIP_Ethernet/src/LwipIntfDev.h#L57

While it is declared here as non-static:
https://github.com/raspberrypi/pico-sdk/blob/efe2103f9b28458a1615ff096054479743ade236/src/rp2_common/pico_cyw43_driver/include/cyw43_configport.h#L125

Removing the static from `LwipIntfDev.h` will fail with multiple definitions during linking, which can be solved by adding `__attribute__((weak))` to the definition in `LwipIntfDev.h`.

**Comment by earlephilhower** [comment]
It was duplicated to avoid needing cyw43 libraries on the other Wifi and Ethernet chips we support. There's nothing on it tied to the cyw chip specifically other than it being part of the sdk.

The simplest solution would be to prefix the name with an underscore in the header and template.  Would you like to do a PR?
