### ISSUE TITLE
Compile error using Wifi.beginAP() on Pico W with Platform IO

### ISSUE THREAD

**Issue by nordseele** [earlephilhower/arduino-pico#865]
Hi, 
I don't know if this issue should be posted here or on Platform IO, I know the integration is a work in progress but I thought it's worth mentioning the compile error I'm getting when using `.beginAP()` in my setup function. I'm using a RPI Pico W and this board doesn't appear yet in PlatformI0. I thought this could be the cause of incompatibility with Pico W, but `Wifi.begin()` doesn't cause any issue. 

Before switching to PlatformIO on Vscode today (fresh install of the extension, I think everything's up to date), I was working with the Arduino IDE 1.8 and didn't have this problem with beginAP(). I don't think I've seen this Access point function in the latest documentation of Arduino-Pico but I've read somewhere in this repo this is what I should use to create an access point on Pico W.

Here's the error raised when building the project: 

```
Linking .pio/build/pico/firmware.elf
/Users/matthias/.platformio/packages/toolchain-rp2040-earlephilhower/bin/../lib/gcc/arm-none-eabi/10.3.0/../../../../arm-none-eabi/bin/ld: .pio/build/pico/src/main.cpp.o: in function `setup':
**main.cpp:(.text.setup+0x12): undefined reference to `_ZN9WiFiClass7beginAPEPKc'**
collect2: error: ld returned 1 exit status
*** [.pio/build/pico/firmware.elf] Error 1
```

Removing `WiFi.beginAP(ssid);` from my setup function, the code now compiles without error.
Only a few warnings, probably related to an OSC library I've recently added, but that's for another issue maybe.

I'm happy to provide more details if needed. 

Thanks.

**Comment by earlephilhower** [comment]
You need to change the board to the PicoW in your compile.  Maybe `board = picow` in the ini file?

**Comment by nordseele** [comment]
Thank you.

Unfortunately, `picoW` is not a known board. Maybe not implemented yet.
Also tried with `picow`, `pico_w`, `pico_W`
What's weird is that Wifi.begin(), doesn't. use any trouble, only beginAP() does.

(I might also ask on the platformIO repo if you prefer, as I also have a question about the board detection and build flags for Pico W)
